package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.shape.Rectangle;

public class AdminController {
	@FXML
	private Rectangle loginBtn;
	@FXML
	private Button regBtn;
	@FXML
	private Button reportBtn;
	@FXML
	private Button logouttBn;

	// Event Listener on Button[#regBtn].onAction
	@FXML
	public void getRegisterPage(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#reportBtn].onAction
	@FXML
	public void getReportsPage(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#logouttBn].onAction
	@FXML
	public void logout(ActionEvent event) {
		// TODO Autogenerated
	}
}
