package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class ReportController {
	private Scene scene;
	private Stage stage;
	private Parent root;
	@FXML
	private Button unregStudId;
	@FXML
	private Button studPerClassId;
	@FXML
	private Button femaleStudPerClassId;
	@FXML
	private Button maleStud;

	// Event Listener on Button[#unregStudId].onAction
	@FXML
	public void unregStud(ActionEvent event) throws IOException {
		// TODO Autogenerated
		root  = FXMLLoader.load(getClass().getResource("application.reports/RegisteredStud.fxml"));
		stage =(Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button[#studPerClassId].onAction
	@FXML
	public void studPerClass(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#femaleStudPerClassId].onAction
	@FXML
	public void femaleStudPerClass(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#maleStud].onAction
	@FXML
	public void maleStudPerClass(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void studPerDept(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void statEnrollByClass(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void statEnrollByDept(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void StatEnrolllbyCycle(ActionEvent event) {
		// TODO Autogenerated
	}
}
